project:
  type: website
  output-dir: docs

website:
  title: "Reproducible Manuscripts in R Workshop"
  sidebar:
    background: "purple"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Workshop"
        contents:
          - href: index.qmd
            text: Home
          - section: "Slides"
            contents:
              - href: slides/workshop-materials.qmd
                text: Materials
              - section: "Introduction"  # Introduction as a parent
                contents:
                  - href: slides/introduction.qmd
                    text: Overview
                  - href: slides/getting-started.qmd
                    text: Getting Started  # Nested under Introduction
              - href: slides/markdown-syntax.qmd
                text: Markdown
              - href: slides/code-chunks.qmd
                text: Analysis
              - href: slides/rendering.qmd
                text: Rendering
format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    fontsize: "18pt"

editor: visual

